"""Synthetic AcmePay engineering history. `rel` lists linked record ids."""
RECORDS = [
 {"id":"INC-101","type":"incident","service":"payment-service","date":"2026-01-14","title":"Payment timeout issue",
  "text":"Payment requests to the card processor timed out and failed without retrying. Root cause: no retry on transient upstream timeouts. Resolved by adding retry with backoff.","rel":["PR-247"]},
 {"id":"PR-247","type":"pull_request","service":"payment-service","date":"2026-01-20","title":"Add retry mechanism to payment client",
  "text":"Introduced retry logic with exponential backoff in the payment client after INC-101 timeouts. Commit a82f91.","rel":["INC-101","a82f91","DEC-01","INC-103"]},
 {"id":"a82f91","type":"commit","service":"payment-service","date":"2026-01-19","title":"feat(payment): retry on timeout","text":"Retry loop with backoff added to payment client.","rel":["PR-247"]},
 {"id":"DEC-01","type":"decision","service":"payment-service","date":"2026-01-18","title":"Retry with backoff over circuit breaker",
  "text":"Decision: use client-side retry with exponential backoff because timeouts were transient. Trade-off: retries can duplicate requests without idempotency.","rel":["PR-247"]},
 {"id":"INC-103","type":"incident","service":"payment-service","date":"2026-03-02","title":"Duplicate payment requests",
  "text":"Duplicate payment requests under timeout conditions. Root cause: retry behavior from PR #247 resent charges without idempotency keys. Fixed by PR #251 adding idempotency protection.","rel":["PR-247","PR-251"]},
 {"id":"PR-251","type":"pull_request","service":"payment-service","date":"2026-03-04","title":"Add idempotency keys to payments",
  "text":"Added idempotency protection because retries could create duplicate payment requests. Fix for INC-103.","rel":["INC-103","DP-v2.4.1"]},
 {"id":"DP-v2.4.1","type":"deployment","service":"payment-service","date":"2026-03-10","title":"Deployment v2.4.1",
  "text":"v2.4.1 shipped idempotency fix. Later saw connection pool exhausted in payment-service (INC-105); pool limits raised and monitoring added.","rel":["PR-251","INC-105"]},
 {"id":"INC-105","type":"incident","service":"payment-service","date":"2026-03-11","title":"Connection pool exhausted",
  "text":"Connection pool exhausted in payment-service after deployment v2.4.1. Resolution: connection limits increased and monitoring added. Error rate returned to normal.","rel":["DP-v2.4.1"]},
 {"id":"INC-102","type":"incident","service":"auth-service","date":"2026-02-05","title":"Authentication token failures",
  "text":"Auth tokens rejected after clock skew between nodes. Resolved by adding token expiry leeway.","rel":["PR-276"]},
 {"id":"INC-104","type":"incident","service":"notification-service","date":"2026-04-08","title":"Notification queue backlog",
  "text":"Notification queue backlog after consumer crash loop. Resolved by scaling consumers and adding dead-letter queue.","rel":["PR-302"]},
 {"id":"PR-318","type":"pull_request","service":"payment-service","date":"2026-05-12","title":"Refactor database connection handling",
  "text":"Refactored database connection management in payment-service.","rel":["DP-v3.1.0"]},
 {"id":"DP-v3.1.0","type":"deployment","service":"payment-service","date":"2026-05-14","title":"Deployment v3.1.0 (rolled back)",
  "text":"v3.1.0 caused latency and error rate increase; deployment was rolled back. Root cause: database connection handling from PR #318 (INC-142).","rel":["PR-318","INC-142"]},
 {"id":"INC-142","type":"incident","service":"payment-service","date":"2026-05-14","title":"Latency and errors after v3.1.0",
  "text":"Latency and error rate rose after v3.1.0; rollback performed. Root cause: database connection handling.","rel":["DP-v3.1.0","PR-318"]},
 {"id":"INC-106","type":"incident","service":"payment-service","date":"2026-04-17","title":"Duplicate charges from repeated payment callbacks",
  "text":"The payment provider retried callbacks after intermittent 5xx responses, and the handler applied the same settlement more than once. Resolution: make callback processing idempotent.","rel":["DEC-02","PR-266"]},
 {"id":"DEC-02","type":"decision","service":"payment-service","date":"2026-04-18","title":"Make payment callbacks idempotent",
  "text":"Decision: use the provider event ID as an idempotency key when processing callbacks. Provider delivery is at least once, so duplicate events must be expected.","rel":["INC-106","PR-266"]},
 {"id":"4ed912","type":"commit","service":"payment-service","date":"2026-04-19","title":"feat(payment): deduplicate provider callbacks",
  "text":"Persisted processed provider event IDs and returned success for duplicate callbacks.","rel":["PR-266"]},
 {"id":"PR-266","type":"pull_request","service":"payment-service","date":"2026-04-20","title":"Deduplicate payment provider callbacks",
  "text":"Added durable idempotency checks for payment callbacks to prevent duplicate settlements. Fix for INC-106, following DEC-02.","rel":["INC-106","DEC-02","4ed912","DP-v2.5.0"]},
 {"id":"DP-v2.5.0","type":"deployment","service":"payment-service","date":"2026-04-24","title":"Deployment v2.5.0",
  "text":"v2.5.0 deployed callback deduplication from PR #266. Duplicate settlements stopped after rollout.","rel":["PR-266"]},
 {"id":"c431e2","type":"commit","service":"auth-service","date":"2026-02-08","title":"fix(auth): allow token expiry leeway",
  "text":"Added a small expiry leeway to token validation to tolerate clock skew between service nodes.","rel":["PR-276"]},
 {"id":"PR-276","type":"pull_request","service":"auth-service","date":"2026-02-09","title":"Allow clock-skew leeway for auth tokens",
  "text":"Added token expiry leeway to prevent valid sessions failing when node clocks differ. Fix for INC-102.","rel":["INC-102","c431e2","DP-v2.6.0"]},
 {"id":"DP-v2.6.0","type":"deployment","service":"auth-service","date":"2026-02-12","title":"Deployment v2.6.0",
  "text":"Released the token expiry leeway fix. Authentication failures caused by node clock skew returned to baseline.","rel":["PR-276"]},
 {"id":"d871ac","type":"commit","service":"notification-service","date":"2026-04-10","title":"feat(notifications): add queue dead-letter handling",
  "text":"Added dead-letter routing and consumer health checks to prevent repeated crash loops from blocking the notification queue.","rel":["PR-302"]},
 {"id":"PR-302","type":"pull_request","service":"notification-service","date":"2026-04-11","title":"Add dead-letter handling for notification jobs",
  "text":"Added dead-letter routing and consumer health checks after the backlog incident INC-104.","rel":["INC-104","d871ac","DP-v2.7.0"]},
 {"id":"DP-v2.7.0","type":"deployment","service":"notification-service","date":"2026-04-15","title":"Deployment v2.7.0",
  "text":"Released dead-letter handling and consumer health checks for notification processing.","rel":["PR-302"]},
]
